export default [
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-04-17',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-03-18',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 10,
    'Submission Date': '2025-01-22',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 10,
    'Submission Date': '2025-01-22',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 123,
    'Submission Date': '2025-05-30',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 2420,
    'Submission Date': '2025-07-08',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-03-04',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-06-05',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 1230,
    'Submission Date': '2025-02-08',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-02-09',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRILE',
    'Full Name Local': 'Lê Nguyên Trí',
    'Full Name English': 'Le Nguyen Tri',
    Gender: 'M',
    'Joining Date': '2024-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': 'Group T',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 27060,
    'Submission Date': '2025-07-24',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'SohuEmp',
    'Full Name Local': 'Hu So TEST',
    'Full Name English': '',
    Gender: '',
    'Joining Date': '2025-06-24',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 100,
    'Submission Date': '2025-09-16',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': '400',
    'Full Name Local': '400 400',
    'Full Name English': '',
    Gender: '',
    'Joining Date': '2025-09-08',
    'Contract Type': 'FT',
    'Location Name': 'Default Location',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '',
    'Organization Element Name': '',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 100,
    'Submission Date': '2025-09-29',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': '400',
    'Full Name Local': '400 400',
    'Full Name English': '',
    Gender: '',
    'Joining Date': '2025-09-08',
    'Contract Type': 'FT',
    'Location Name': 'Default Location',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '',
    'Organization Element Name': '',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 2200,
    'Submission Date': '2025-11-13',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': '400',
    'Full Name Local': '400 400',
    'Full Name English': '',
    Gender: '',
    'Joining Date': '2025-09-08',
    'Contract Type': 'FT',
    'Location Name': 'Default Location',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '',
    'Organization Element Name': '',
    'Claim Type': '321312323',
    'Pay Element': '',
    'Claim Amount': 2222200000000000,
    'Submission Date': '2025-11-13',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': '400',
    'Full Name Local': '400 400',
    'Full Name English': '',
    Gender: '',
    'Joining Date': '2025-09-08',
    'Contract Type': 'FT',
    'Location Name': 'Default Location',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '',
    'Organization Element Name': '',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 100,
    'Submission Date': '2025-09-16',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 555555,
    'Submission Date': '2024-10-30',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-02-06',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 12,
    'Submission Date': '2025-04-09',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Meal Claim',
    'Pay Element': '',
    'Claim Amount': 111111111,
    'Submission Date': '2025-02-08',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-02-08',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 22000000,
    'Submission Date': '2025-11-27',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 660,
    'Submission Date': '2025-11-05',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-06-05',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'HAIVU',
    'Full Name Local': 'Vũ Đình Hải',
    'Full Name English': 'Vu Dinh Hai',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group H',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-01-23',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Phone Claim',
    'Pay Element': '',
    'Claim Amount': 125000,
    'Submission Date': '2025-04-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Parking Claim',
    'Pay Element': '',
    'Claim Amount': 10000000,
    'Submission Date': '2025-06-25',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Traveling Claim',
    'Pay Element': '',
    'Claim Amount': 1000000,
    'Submission Date': '2025-06-25',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 10000000,
    'Submission Date': '2025-06-20',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': '321',
    'Pay Element': '',
    'Claim Amount': 100,
    'Submission Date': '2025-09-16',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 1,
    'Submission Date': '2025-06-10',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH001',
    'Full Name Local': 'Bùi Anh Tuấn',
    'Full Name English': 'Mike',
    Gender: '',
    'Joining Date': '2024-10-01',
    'Contract Type': 'FT',
    'Location Name': 'Hoàng Quốc Việt',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': '2Center 12',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 1231,
    'Submission Date': '2025-06-01',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 1,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Traveling Claim',
    'Pay Element': '',
    'Claim Amount': 123123,
    'Submission Date': '2025-03-28',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Transport Claim',
    'Pay Element': '',
    'Claim Amount': 1111111111111,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 2222222,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 3333333,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 2,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 44444,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 11111,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Traveling Claim',
    'Pay Element': '',
    'Claim Amount': 123,
    'Submission Date': '2025-03-28',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 111,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 2,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 3,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 111,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 222,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 4,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 1231230,
    'Submission Date': '2025-01-23',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 5,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 123123,
    'Submission Date': '2025-01-23',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 6,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Meal Claim',
    'Pay Element': '',
    'Claim Amount': 1231231230,
    'Submission Date': '2025-01-23',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 7,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 8,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 9,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'NGOCNGUYEN',
    'Full Name Local': 'Nguyễn Thế Ngọc',
    'Full Name English': 'Nguyen The Ngoc',
    Gender: 'M',
    'Joining Date': '2025-01-01',
    'Contract Type': '',
    'Location Name': 'Default Location',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group B',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 10,
    'Submission Date': '2025-03-21',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Transport Claim',
    'Pay Element': '',
    'Claim Amount': 200000,
    'Submission Date': '2025-01-09',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 99999,
    'Submission Date': '2025-01-28',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 123123,
    'Submission Date': '2025-02-07',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Phone Claim',
    'Pay Element': '',
    'Claim Amount': 123123123123,
    'Submission Date': '2025-02-07',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Transport Claim',
    'Pay Element': '',
    'Claim Amount': 2222222,
    'Submission Date': '2025-01-09',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Transport Claim',
    'Pay Element': '',
    'Claim Amount': 123123123,
    'Submission Date': '2025-02-07',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Transport Claim',
    'Pay Element': '',
    'Claim Amount': 44444,
    'Submission Date': '2025-01-09',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 0,
    'Submission Date': '2025-03-18',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Transport Claim',
    'Pay Element': '',
    'Claim Amount': 12312312312,
    'Submission Date': '2025-03-18',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Mileage Claim',
    'Pay Element': '',
    'Claim Amount': 123123123,
    'Submission Date': '2025-03-18',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Accommodation Claim',
    'Pay Element': '',
    'Claim Amount': 23123123,
    'Submission Date': '2025-03-18',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Phone Claim',
    'Pay Element': '',
    'Claim Amount': 21312,
    'Submission Date': '2025-03-18',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Traveling Claim',
    'Pay Element': '',
    'Claim Amount': 50000000,
    'Submission Date': '2025-05-28',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'TRUNGLE',
    'Full Name Local': 'Vũ Quốc Thiên',
    'Full Name English': 'Vu Quoc Thien',
    Gender: 'M',
    'Joining Date': '2024-10-03',
    'Contract Type': '',
    'Location Name': '',
    'Job Position Name': '',
    'Cost Center Name': '',
    'Organization Element Name': 'Group K',
    'Claim Type': 'Traveling Claim',
    'Pay Element': '',
    'Claim Amount': 11111223,
    'Submission Date': '2025-02-07',
    'Paid Status': 'No',
  },
  {
    'Employee Ref': 'DH002',
    'Full Name Local': 'Bùi Thị Diễn Châu',
    'Full Name English': '',
    Gender: 'F',
    'Joining Date': '2025-07-08',
    'Contract Type': '',
    'Location Name': 'Zigvy',
    'Job Position Name': 'JobPos 1',
    'Cost Center Name': 'Saigon Center',
    'Organization Element Name': '',
    'Claim Type': 'Child-care Claim',
    'Pay Element': '',
    'Claim Amount': 123,
    'Submission Date': '2025-06-02',
    'Paid Status': 'No',
  },
];
